### PR TITLE
Fix the Behat tests for the latest filter changes.

### PR DESCRIPTION
**Pull request by timhunt**
Your recent changes to the filter has stopped my behat tests working. Here is a fix. However, it request a fix to Moodle core to work.

### CODE REVIEW

**Comment by timhunt** [comment]
The Moodle core fix this needs is MDL-52899.

**Comment by timhunt** [comment]
https://tracker.moodle.org/browse/MDL-52899

**Comment by geoffrowland** [comment]
Thanks Tim. Your work on this is much appreciated. 
Still not got behat setup at this end :-(
I guess I should revisit.
Have voted for MDL-52899 ;-)

**Comment by timhunt** [comment]
No worries. Thanks for making this plugin. Behat is a pain to get working the first time, but one you have it set up, it is so much better than testing things by hand!

**Pull request merged**
